# -*- coding: utf-8 -*-
#
# Copyright (C) 2018-2020 CERN.
#
# CDS-ILS is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.


notifications:
  email: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - postgresql
  - redis
  - rabbitmq

addons:
  postgresql: "12.4"

env:
  global:
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.1-linux-x86_64.tar.gz"
    - ES_HOST=127.0.0.1
    # Needed after release of v50.0.0 of setuptools (Setuptools overrides the stdlib distutils on import) [temporary solution]
    - SETUPTOOLS_USE_DISTUTILS="stdlib"

python:
  - "3.6"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES7_DOWNLOAD_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "sleep 20"
  - "nvm install 12; nvm use 12"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls"

install:
  - "./scripts/bootstrap"

script:
  - ./run-tests.sh

after_success:
  - coveralls
